Feature/tests with environments
indigotech/onboard-jorge-risco pull request #18
Opened 2021-01-15 18:45 UTC by jorgemrisco

Added login mutation test, which adds an user to the database, validates that user and then clears the User table.

2021-01-15 21:45 UTC, matheusflds commented on package.json
> +    "@types/chai": "^4.2.14",
fixar o chai

2021-01-15 21:48 UTC, matheusflds commented on test/test.ts
> +  it('should return user "Fulano"', async () => {
como vc implementou o rememberMe, ja dava pra ter um teste cobrindo o login com e sem essa opção. E ai precisaria checar o exp do token também

2021-01-15 21:50 UTC, matheusflds commented on test/test.ts
> +    checkToken(response.body.data.login.token);
aqui você usa uma função que criou no arquivo .crypto que valida se o token é válido e só né? Talvez verificar se o payload está correto também.
Lembrando de utilizar o expect para fazer as asserções do conteúdo do token, para poder visualizar melhor após rodar os testes. Isso porque se o seu projeto tivesse muitos testes, grandes chances do console.log do checkToken sumir no meio da selva de byte haha

2021-01-18 12:57 UTC, alanraso requested changes
Os testes são pra você verificar se o servidor se comporta conforme o esperado considerando o máximo de cenários possíveis. Nesse sentido, testar apenas o caso de um login com succeso, e testar apenas o campo nome perde bastante a efetividade deles

2021-01-18 12:57 UTC, alanraso commented on test/test.ts
> +=======
Isso deve ter vindo de conflito

2021-01-18 12:57 UTC, alanraso commented on test/test.ts
> +    usersRepo.clear();
Aqui é melhor usar um await, senão pode ser que ele passe pro próximo teste sem ter terminado essa tarefa de clear.

2021-01-18 12:57 UTC, alanraso commented on test/test.ts
> +          token
Aqui acho que seria interessante você reutilizar o texto da mutation em outros testes (próximo comentário eu falo sobre o número de testes), usando as vairáveis do GraphQL. Outra coisa interessante seria você testar com o retorno de todos os campos possíveis, que seria o caso de maior cobertura do testes, pois ele testaria se todos os campos vieram do banco com sucesso.

2021-01-18 17:49 UTC, alanraso commented on src/crypto.ts
> +}
Acho que ficou meio redundante aqui. Vc pode usar qualquer uma das duas funções pra validar um token, mas as duas não é necessário 🤔

2021-01-18 17:49 UTC, alanraso commented on test/test.ts
> +  });
Aqui tem algo semelhante ao que eu comenteu no review anterior: sem o await, essas funções vão ser chamadas e enquanto a query pro banco é feita (que é uma tarefa assíncrona), o código vai tocando. Então pode ser que ele faça o teste sem ter terminado isso aqui. Melhor colocar os `await`s  pra garantir, certo?

2021-01-18 17:49 UTC, alanraso commented on test/test.ts
> +    console.log(response.body.data.login.user);
Esse log não precisa mais, né?

2021-01-18 17:49 UTC, alanraso commented on test/test.ts
> +    expect(response.body.data.login.user.cpf).to.be.eq('1');
Boa, agora testando todos os campos o teste fica mais confiável.

2021-01-18 17:49 UTC, alanraso commented on test/test.ts
> +  return query;
Dá pra retornar direto o objeto:

```ts
return {
  query: `mutation...
```

2021-01-18 17:49 UTC, alanraso approved these changes

2021-01-18 18:37 UTC, matheusflds approved these changes

2021-01-19 13:03 UTC, merged